export default [
    //Michael Jackson
    {value: "2ZytN2cY4Zjrr9ukb2rqTP", label: "Off The Wall"},
    {value: "2ANVost0y2y52ema1E9xAZ", label: "Thriller"},
    {value: "3Us57CjssWnHjTUIXBuIeH", label: "Bad"},
    {value: "0oX4SealMgNXrvRDhqqOKg", label: "Dangerous"},
    {value: "3OBhnTLrvkoEEETjFA3Qfk", label: "HIStory: Past, Present and Future, Book 1"},
    {value: "0RNsFWWdiz1rrdLI1pwbvJ", label: "Blood on the Dance Floor: HIStory in the Mix"},
    {value: "52E4RP7XDzalpIrOgSTgiQ", label: "Invincible"},
    {value: "5S7ySBYbWKsZdVYQrNtrWf", label: "Michael"},
    {value: "7pomP86PUhoJpY3fsC0WDQ", label: "XSCAPE"},
    //Queen
    {value: "64axF9Amc2ExcZbFs8btdv", label: "Queen"},
    {value: "6Cg1pPfnfFXlR1qH2H6NDL", label: "Queen II"},
    {value: "5CooX2xg5YibepSfjbRFNT", label: "Sheer Heart Attack"},
    {value: "7HVoV2lgVsmuiHsjbbUJB4", label: "A Night at the Opera"},
    {value: "4kmYoWtWvAIS43KwGuRb50", label: "A Day at the Races"},
    {value: "3TKTjR4E3LAMfRsPeRsNhT", label: "News of the World"},
    {value: "5X3rA8To5GDOeIWdQyMEcE", label: "Jazz"},
    {value: "1h0j80HhdzIMsUGUFiVkqa", label: "The Game"},
    {value: "0fZCqpTHYq2k89uG6pPTYE", label: "Hot Space"},
    {value: "0FbnXAGmgmWBmNthZSgm43", label: "The Works"},
    {value: "34xBXeJgmQrn1wQvhyVCsw", label: "A Kind of Magic"},
    {value: "0kCPII9EM5eqHHCRo1EVjs", label: "The Miracle"},
    {value: "5yAM3CcaXF6DPRJW3oL6Ya", label: "Innuendo"},
    {value: "2SFIh6siY4KYBNPHAV7xaI", label: "Made in Heaven"},
    //Kanye West
    {value: "4Uv86qWpGTxf7fU7lG5X6F", label: "The College Dropout"},
    {value: "5ll74bqtkcXlKE7wwkMq4g", label: "Late Registration"},
    {value: "0veuYKXCayS7oIfyqlibeR", label: "Late Orchestration"},
    {value: "4SZko61aMnmgvNhfhgTuD3", label: "Graduation"},
    {value: "3WFTGIO6E3Xh4paEOBY9OU", label: "808s & Heartbreak"},
    {value: "20r762YmB5HeofjMCiPMLv", label: "My Beautiful Dark Twisted Fantasy"},
    {value: "7mCeLbChyegbRwwKK5shJs", label: "Watch the Throne"},
    {value: "7D2NdGvBHIavgLhmcwhluK", label: "Yeezus"},
    {value: "7gsWAHLeT0w7es6FofOXk1", label: "The Life of Pablo"},
    {value: "2Ek1q2haOnxVqhvVKqMvJe", label: "ye"},
    {value: "6pwuKxMUkNg673KETsXPUV", label: "KIDS SEE GHOSTS"},
    {value: "0FgZKfoU2Br5sHOfvZKTI9", label: "Jesus Is King"},
    {value: "5CnpZV3q5BcESefcB3WJmz", label: "Donda"},
    //Playboi Carti
    {value: "4rJgzzfFHAVFhCSt2P4I3j", label: "Playboi Carti"},
    {value: "7dAm8ShwJLFm9SaJ6Yc58O", label: "Die Lit"},
    {value: "2QRedhP5RmKJiJ1i8VgDGR", label: "Whole Lotta Red"},
    //Travis Scott
    {value: "4PWBTB6NYSKQwfo79I3prg", label: "Rodeo"},
    {value: "42WVQWuf1teDysXiOupIZt", label: "Birds in the Trap Sing McKnight"},
    {value: "6FED8aeieEnUWwQqAO9zT1", label: "Huncho Jack, Jack Huncho"},
    {value: "41GuZcammIkupMPKH2OJ6I", label: "ASTROWORLD"},
    //Tyler, The Creator
    {value: "5dbCm8qaCdWnNdVyi3urUO", label: "Goblin"},
    {value: "40QTqOBBxCEIQlLNdSjFQB", label: "Wolf"},
    {value: "621OhgnZJ7Pz8iUazct1In", label: "Cherry Bomb"},
    {value: "2nkto6YNI4rUYTLqEwWJ3o", label: "Flower Boy"},
    {value: "5zi7WsKlIiUXv09tbGLKsE", label: "IGOR"},
    {value: "45ba6QAtNrdv6Ke4MFOKk9", label: "Call Me If You Get Lost"},

    ];